### ISSUE TITLE
Preview fails to spawn command

### ISSUE THREAD

**Issue by hajdamak** [skim-rs/skim#222]
Calling:
`ls | sk  --preview '/bin/echo' `
results in error message displayed in preview window:
`Failed to spawn: /bin/echo / No such file or directory (os error 2) `
Skim version 0.6.9
Ubuntu 16.04.06 LTS

**Comment by lotabout** [comment]
@hajdamak could you please run the command with `${SHELL:-sh} -c '/bin/echo'` in your shell and check what happens? Internally skim will invoke this command.

**Comment by hajdamak** [comment]
In Fish I get:
```
fish: ${ is not a valid variable in fish.
${SHELL:-sh} -c '/bin/echo'
 ^
```
In Bash it just prints empty line.
Note however that I get  failed to spawn message in both Fish and Bash

**Comment by hajdamak** [comment]
I have now tried on Fedora 30 and everything works fine.

**Comment by lotabout** [comment]
@hajdamak Could you please try using `echo` instead of `/bin/echo` and see if there is a difference?

**Comment by hajdamak** [comment]
Same problem on Ubuntu.

**Comment by victorz** [comment]
The fact that you are missing `/bin/echo` is odd. What happens if you run `[ -x /bin/echo ] && echo exists || echo does not exist` in the terminal?

Other than that, I do believe you need to use `{}` in the command string to be able to see something.

    ls | sk --preview '/bin/echo {}'

Try without the `/bin/` as well?

    ls | sk --preview 'echo {}'
