### ISSUE TITLE
Would you consider adding feature gate for cli and library?

### ISSUE THREAD

**Issue by pombadev** [skim-rs/skim#289]
Since we can already use this as a [library](https://github.com/lotabout/skim/blob/a13bd4b1bf/README.md#use-as-a-library), i think it will be beneficial to separate them so that if someone consume this as a library, we don't pull un-needed crates (eg: clap).

**Comment by lotabout** [comment]
Waiting for https://github.com/rust-lang/cargo/issues/1982

**Comment by bedax** [comment]
In the mean time, an option would be to have something like this:

```
bin = ["clap", ...]
default = ["bin"]
```

And then library users can disable default-features.

**Comment by pjmp** [comment]
@lotabout thanks for the response. You can either close this issue or keep it opened as you see fit, thanks!

**Comment by LoricAndre** [comment]
I think this has been implemented in the meantime, please reopen if I'm wrong
