### ISSUE TITLE
Reading SKIM_DEFAULT_OPTIONS when used as a library

### ISSUE THREAD

**Issue by MikeCain** [skim-rs/skim#390]
Hi,
I looked a little into using skim as a library, but it didn't look as though there was a way to pick up on the system-defined options like `SKIM_DEFAULT_OPTIONS` and `SKIM_DEFAULT_COMMAND`.

Does library skim have this functionality?  If not, I'm interested in the potential work involved in adding that.

Thank you very much for your work on this, by the way.

**Comment by lotabout** [comment]
Currently `SKIM_DEFAULT_OPTIONS` is picked up by [main.rs](https://github.com/lotabout/skim/blob/master/src/bin/main.rs#L160), converted to `SkimOptions` and passed to skim library. I'd like to keep it this way for separation concern.

I understand that reading options from environment variable could be convenient when working with skim library. Helpers might be added for constructing `SkimOptions` **outside** library in the future.
