### ISSUE TITLE
Add an option to specify how much to scroll on preview-up/preview-down

### ISSUE THREAD

**Issue by AlexCzar** [skim-rs/skim#398]
When I'm reading the text in the preview and have to scroll, the text jumping by a whole page breaks the reading flow.
If possible, please, add an option that a user could set to make the preview scroll by N lines.
(fzf just scrolls by 1 line, which also would be fine for me, personally, but I imagine some peple do prefer whole page or something between that and 1 line).

**Comment by sitaktif** [comment]
I think this issue can be closed.
