### ISSUE TITLE
Ability to customize interactive mode `ctrl-q` binding

### ISSUE THREAD

**Issue by ibhagwan** [skim-rs/skim#425]
When using interactive mode, I’d like to use another key to switch between command and query modes, the default is set to `ctrl-q`, I read both the README and man page and couldn’t find how to do it - is that even possible?

if not, would it be possible to add this customization?

**Comment by AndydeCleyre** [comment]
It's worth noting on this issue that `ctrl`-`q` quits `fzf`, so folks trying to use this interchangeably may stumble on the current behavior of skim.
