### ISSUE TITLE
Bright ansi colors (ansi codes > 7) do not work

### ISSUE THREAD

**Issue by tobx** [skim-rs/skim#434]
This displays the first line in _red_ and the second in _bright red:_
```bash
echo -e "$(tput setaf 1)Red\n$(tput setaf 9)Bright Red"
```
The bright colors are not showing with skim:
```bash
echo -e "$(tput setaf 1)Red\n$(tput setaf 9)Bright Red" | sk --ansi
```

I tried this in Ubuntu and on macOS (default terminal applications).

**Comment by LoricAndre** [comment]
Could not reproduce
