### ISSUE TITLE
Please implement std::fmt::Debug for SkimOptions

### ISSUE THREAD

**Issue by petr-tik** [skim-rs/skim#441]
hey, thanks for the awesome crate to create interactive fuzzy UIs! 

I was trying to work out which skim_options were set to which values with a dbg! macro and found this error

```bash
error[E0277]: `SkimOptions<'_>` doesn't implement `std::fmt::Debug`
    |
218 |     dbg!(&skim_options);
    |     ^^^^^^^^^^^^^^^^^^^ `SkimOptions<'_>` cannot be formatted using `{:?}` because it doesn't implement `std::fmt::Debug`
    |
    = help: the trait `std::fmt::Debug` is not implemented for `SkimOptions<'_>`
```

The Rust lang API guidelines suggest eagerly implementing the Debug trait for crate's public types. 

https://rust-lang.github.io/api-guidelines/debuggability.html#c-debug
https://rust-lang.github.io/api-guidelines/interoperability.html#c-common-traits

I found it quite tricky to navigate between different SkimOptions (eg. what is the difference between cmd_prompt and prompt?), so I would appreciate if I could and check it out

```rust
dbg!(skim_options);
```

thanks again for the awesome library

**Comment by LoricAndre** [comment]
Sorry, but this isn't possible to implement, because some fields in `SkimOptions` are boxed `dyn Trait`s, for which it is not really possible to implement `Debug` AFAIK
