### ISSUE TITLE
Smart CD with Preview

### ISSUE THREAD

**Issue by blueray453** [skim-rs/skim#462]
I am using `0.9.4`

I want to fuzzy search all sub-directories and cd to the selected one when pressed enter.

What I tried so far is:

    fd -t d | sk --ansi -i --bind 'enter:execute(cd {})' --preview 'cd "{}"'

It is giving error: 

    zsh:cd:1: no such file or directory: './Desktop/'

**Comment by theherk** [comment]
Why not just `cd $(fd -t d | sk)`?
