### ISSUE TITLE
Ctrl_R to Show History in ZSH

### ISSUE THREAD

**Issue by blueray453** [skim-rs/skim#463]
The widget I worked till now is:

```
skim-history() {
  origquery=${BUFFER}
  output=$(history -1 1 | sd '^[ ]*[0-9]*[ ]*' '' | sk --tac --no-sort --exact)

  if [ $? -eq 0 ]; then
    BUFFER=$output
  else
    BUFFER=$origquery
  fi

  CURSOR=$#BUFFER
}

zle     -N   skim-history
bindkey '^R' skim-history
```

It is working fine except mult-line command.

Instead of showing multi-line commands like:
![Screenshot-2022-07-07-12:49:45](https://user-images.githubusercontent.com/855297/177710016-18996732-8fb6-43f0-8ee5-da861d45f113.png)
It shows it like:
![Screenshot-2022-07-07-12:50:01](https://user-images.githubusercontent.com/855297/177710066-a8792fd4-af58-4e3d-b400-1c203e5adf6b.png)

I mean it replaces newline with `\n`

How can I solve this problem?

**Comment by LoricAndre** [comment]
I don't think this is possible, we need to fit each item in one line. I am closing this issue, if you really want to output the item in multiple lines you should be able to achieve this with `--preview`.

**Comment by LoricAndre** [comment]
Note : I tweaked a preview arg for zsh using bat, you could use:
```zsh
export SKIM_CTRL_R_OPTS='--preview="echo {4..} | bat --plain --language zsh --color=always"'
```
