### ISSUE TITLE
Question: Reload command

### ISSUE THREAD

**Issue by pleshevskiy** [skim-rs/skim#473]
Is it possible to reload command like in `fzf` https://github.com/junegunn/fzf#reloading-the-candidate-list ?

**Comment by familyfriendlymikey** [comment]
https://github.com/lotabout/skim#as-interactive-interface

**Comment by pleshevskiy** [comment]
Seems like I have to change query to reload my command :( It will not work for me

**Comment by classabbyamp** [comment]
you can bind something to the `reload-cmd` action as of 0.9.2, e.g. `--bind=ctrl-r:reload-cmd`

**Comment by dkasak** [comment]
@classabbyamp Where is this `reload-cmd` action exactly? I can't find any reference to it anywhere.

**Comment by LoricAndre** [comment]
Is there any progress on this ?
