### ISSUE TITLE
UI recently broken on zellij

### ISSUE THREAD

**Issue by happysalada** [skim-rs/skim#482]
I do not know why but the skim UI has recently broken.
I'm using zellij as a terminal, rather than show the different results on top of the current typing windown, it now shows everything in a line.

<img width="1280" alt="Screen Shot 2022-10-23 at 9 37 43 AM" src="https://user-images.githubusercontent.com/5317234/197395493-bdf24244-4032-4523-b66f-82d87716aa97.png">

I'm not sure exactly what is the cause of this, but would love to help debug if need be.

**Comment by EdenEast** [comment]
I can report the same issues wezterm (20220808-211601-d2892c6f) and alacritty (0.11.0). This does not happen on kitty (0.25.2). It does however happen in kitty when using tmux. This is all on an intel mac.

**Comment by linuxmobile** [comment]
Has anyone found a solution to this problem? it's still in my Zellij Config

**Comment by LoricAndre** [comment]
Could you please share more details about your setup ? Which terminal emulator are you using ? I wasn't able to reproduce this with the default zellij config on either kitty or alacritty on linux.

**Comment by happysalada** [comment]
Hey thank you for responding.
Ive tested on latest and i cant see the issue anymore.
Im using nushell and a nushell integration command would be amazing.
Atuin has a nice integration with nushell fir example.
Thank you for making skim !
