### ISSUE TITLE
binary availability

### ISSUE THREAD

**Issue by fragolinux** [skim-rs/skim#531]
hi, it seems like moving from 0.9.4 to 0.10.0 [broke ](https://github.com/lotabout/skim/actions/workflows/publish-github.yml)your CI toolchain, and binaries are now no longer published on your releases page...

can you fix this? I'd like to help to create an "[asdf](https://github.com/asdf-vm/asdf-plugin-template)" plugin, to have versioned binaries, but if no binaries are available, it's a bit difficult :D 

or, better, if you add this functionality directly in your builds :)

**Comment by ClementNerma** [comment]
I'd also really like to have a binary available, especially in the Github releases like many Rust (and non-Rust) tools do :)

**Comment by LoricAndre** [comment]
This should be fixed, I'm closing the issue.
