### ISSUE TITLE
SKIM_TMUX=1 causes tmux pane to freeze with zsh

### ISSUE THREAD

**Issue by nrdxp** [skim-rs/skim#558]
I started experiencing some bizarre behavior just today that I thought was rather strange as I have been using the same setup for literally years now and never experienced this issue once. Basically, all of a sudden, when I try to use my key bind commands in zsh, only when inside a tmux session, say if I press <kbd>alt-c</kbd> then sk does open as usual, but when it exits the terminal just kinda freezes. It's not really frozen cause the cursor still blinks, and strace reveals that it is still recieving inputs, but it doesn't respond visually and nothing I do to try to reset it works.

The only option is to close the pane and open a new one to regain access to the terminal. After trying to narrow it down I realized that if I `unset SKIM_TMUX` then this behavior magically disappears and everything works as normal again, besides the fact that skim no longer opens in a new tmux pane.

To try and narrow it down further, I realized I can invoke `SKIM_TMUX=1 skim-cd-widget` command to reproduce the behavior. Doing this causes me to lose access to the shell, the only difference being that if I use the keybind none of my input registers visually, but if I call the function I can see the key presses in the terminal pane, but somehow control never returns to the terminal and I'm just stuck in the same way as described above unless I close the pane.

This happens for any of the keybind commands, I just used <kbd>alt-c</kbd> as an example here.

**Comment by LoricAndre** [comment]
I can't reproduce this, can you share more precise reproduction steps please ?
