### ISSUE TITLE
feature request: add default key bindings for bash / zsh / fish shell

### ISSUE THREAD

**Issue by j-lakeman** [skim-rs/skim#569]
Quite like the keybinding method of `fzf`: https://github.com/junegunn/fzf?tab=readme-ov-file#key-bindings-for-command-line
Would be cool if `skim` could also get that!

I prefer it over `fzf` for performance issues.

**Comment by LoricAndre** [comment]
This should already be included. How did you install and set up skim ?
See https://github.com/skim-rs/skim/blob/master/shell/key-bindings.zsh for example

**Comment by j-lakeman** [comment]
I tried both on Alpine and macOS through brew, but neither `CTRL-T` nor `CTRL-R` nor `ALT-C` seem to work OOTB.
Possibly the shell bindings don’t get included by the package maintainers?

**Comment by LoricAndre** [comment]
Yes, unfortunately we don't manage the packaging atm.
You could source the file yourself, which should enable the bindings for your current session (and add it to `bashrc`/`zshrc` to make it persistent). Where you can find the file on your system, if you can find it at all, is dependant on the package manager too, so you could download it from the repo yourself if you want an easier (but more manual) way.

**Comment by j-lakeman** [comment]
Would be awesome if `skim` did that as well: https://github.com/junegunn/fzf?tab=readme-ov-file#setting-up-shell-integration
That’d be quite straightforward for the users IMHO.

Will try to get package maintainers to include shell integrations also.

**Comment by LoricAndre** [comment]
We'll add this to our backlog, it would be pretty nice !

**Comment by LoricAndre** [comment]
If you made the key bindings work on your PC could you please close this ?
