### ISSUE TITLE
Request: --no-info / --info=hidden

### ISSUE THREAD

**Issue by AndydeCleyre** [skim-rs/skim#593]
For increased compatibility with fzf, it would be great to have `--no-info` / `--info=hidden`.

These are the descriptions of those options in fzf, along with the other info styles fzf supports. Accepting those other styles would increase compatibility further, but this request is just for the hidden style.

```man
--info=STYLE
       Determines the display style of finder info.

       default       Display on the next line to the prompt
       inline        Display on the same line
       hidden        Do not display finder info

--no-info
       A synonym for --info=hidden
```

Here are side-by-side comparisons. From left to right: fzf default, fzf inline, fzf hidden, skim:

![image](https://github.com/user-attachments/assets/e6d97326-36cc-4560-95f7-66b791cc99e8)

**Comment by LoricAndre** [comment]
We have quite a few PRs in the works right now, but we'll add this to our backlog !
