### ISSUE TITLE
Shell reverse search broken since 0.11.11

### ISSUE THREAD

**Issue by freswa** [skim-rs/skim#610]
Running skim on MacOS with the key-bindings from the repo sourced. When pressing <Ctrl+R> I get:

```
 ❯ error: invalid value 'index' for '--tiebreak <TIEBREAK>'
[possible values: score, -score, begin, -begin, end, -end, length, -length]

For more information, try '--help'.
```

**Comment by LoricAndre** [comment]
The `index` tiebreak has been gone for years now (I am working on readding it).
We'll start working on a fix right away, in the meantime you could remove the `--tiebreak=index` from the sourced keybinding files, unfortunately their location depends on how they are installed.

**Comment by LoricAndre** [comment]
This should be fixed in the latest release. Depending on how skim is installed, this could take some time to propagate to homebrew or other repos.

**Comment by freswa** [comment]
lgtm. Thank you!
