### ISSUE TITLE
multiple bind `--expect` broken in recent releases (up to 0.13)

### ISSUE THREAD

**Issue by ibhagwan** [skim-rs/skim#622]
The below works with v10.0.4 but doesn't work with v0.12/v0.13:
```sh
sk --expect="ctrl-y,ctrl-g"
```

Recent releases only work with one key in `--expect`, both below work:
```sh
sk --expect="ctrl-y"                    # Works with only one key
sk --expect="ctrl-y" --expect="ctrl-g"  # Works if split into multiple flags
```

It might also be worth noting that fzf recently moved away from the `--expect` approach (had issues combining actions with expect, see https://github.com/junegunn/fzf/issues/3810) and instead added the more versatile `print(...)` action so it's now possible to emulate (and expand) on `--expect` with:
> For example, using `ctrl-q` to select-all+accept without losing the bind context in the final results
```sh
fzf --bind ctrl-q:select-all+print(ctrl-q)+accept
```

**Comment by LoricAndre** [comment]
Same issue with `--nth` and similar arguments
